// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBiddable.Library.EF;

namespace Ccd.Bidding.Manager.Library.Migrations;

[DbContext(typeof(Dbc))]
[Migration("20200916120540_update")]
partial class update
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "3.1.6")
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("ccd.bm.lib.Bid", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.ToTable("Bids");
            });

        modelBuilder.Entity("ccd.bm.lib.Item", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("BidId")
                    .HasColumnType("int");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Last_Order_Price")
                    .HasColumnType("decimal(18,5)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,5)");

                b.Property<bool>("Substitutable")
                    .HasColumnType("bit");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.HasIndex("BidId");

                b.ToTable("Items");
            });

        modelBuilder.Entity("ccd.bm.lib.LineItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("AccountNumber")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Description")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Note")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("PartNumber")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,5)");

                b.Property<int?>("PurchaseOrderId")
                    .HasColumnType("int");

                b.Property<decimal?>("Quantity")
                    .HasColumnType("decimal(18,5)");

                b.Property<string>("Unit")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.HasIndex("PurchaseOrderId");

                b.ToTable("LineItems");
            });

        modelBuilder.Entity("ccd.bm.lib.PurchaseOrder", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("BidId")
                    .HasColumnType("int");

                b.Property<string>("Building")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<DateTime>("CreationDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Vendor")
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.HasKey("Id");

                b.HasIndex("BidId");

                b.ToTable("PurchaseOrders");
            });

        modelBuilder.Entity("ccd.bm.lib.Request", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Account_Number")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<int?>("RequestorId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RequestorId");

                b.ToTable("Requests");
            });

        modelBuilder.Entity("ccd.bm.lib.RequestItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("ItemId")
                    .HasColumnType("int");

                b.Property<decimal>("OverridePrice")
                    .HasColumnType("decimal(18,5)");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<int?>("RequestId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ItemId");

                b.HasIndex("RequestId");

                b.ToTable("RequestItems");
            });

        modelBuilder.Entity("ccd.bm.lib.Requestor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("BidId")
                    .HasColumnType("int");

                b.Property<string>("Building_Name")
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasMaxLength(50);

                b.Property<string>("Building_Number")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasMaxLength(255);

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("varchar(30)")
                    .HasMaxLength(30);

                b.HasKey("Id");

                b.HasIndex("BidId");

                b.ToTable("Requestors");
            });

        modelBuilder.Entity("ccd.bm.lib.ResponseItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("AlternateDescription")
                    .HasColumnType("nvarchar(500)")
                    .HasMaxLength(500);

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)")
                    .HasMaxLength(50);

                b.Property<bool>("Elected")
                    .HasColumnType("bit");

                b.Property<bool>("IsAlternate")
                    .HasColumnType("bit");

                b.Property<int>("ItemId")
                    .HasColumnType("int");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,5)");

                b.Property<decimal>("Quantity")
                    .HasColumnType("decimal(18,5)");

                b.Property<string>("ReasonElected")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Unit")
                    .IsRequired()
                    .HasColumnType("nvarchar(30)")
                    .HasMaxLength(30);

                b.Property<int?>("VendorResponseId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ItemId");

                b.HasIndex("VendorResponseId");

                b.ToTable("ResponseItems");
            });

        modelBuilder.Entity("ccd.bm.lib.VendorResponse", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int?>("BidId")
                    .HasColumnType("int");

                b.Property<string>("VendorName")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)")
                    .HasMaxLength(100);

                b.HasKey("Id");

                b.HasIndex("BidId");

                b.ToTable("VendorResponses");
            });

        modelBuilder.Entity("ccd.bm.lib.Item", b =>
            {
                b.HasOne("ccd.bm.lib.Bid", "Bid")
                    .WithMany("Items")
                    .HasForeignKey("BidId");
            });

        modelBuilder.Entity("ccd.bm.lib.LineItem", b =>
            {
                b.HasOne("ccd.bm.lib.PurchaseOrder", "PurchaseOrder")
                    .WithMany("LineItems")
                    .HasForeignKey("PurchaseOrderId");
            });

        modelBuilder.Entity("ccd.bm.lib.PurchaseOrder", b =>
            {
                b.HasOne("ccd.bm.lib.Bid", "Bid")
                    .WithMany("PurchaseOrders")
                    .HasForeignKey("BidId");
            });

        modelBuilder.Entity("ccd.bm.lib.Request", b =>
            {
                b.HasOne("ccd.bm.lib.Requestor", "Requestor")
                    .WithMany("Requests")
                    .HasForeignKey("RequestorId");
            });

        modelBuilder.Entity("ccd.bm.lib.RequestItem", b =>
            {
                b.HasOne("ccd.bm.lib.Item", "Item")
                    .WithMany()
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ccd.bm.lib.Request", "Request")
                    .WithMany("RequestItems")
                    .HasForeignKey("RequestId");
            });

        modelBuilder.Entity("ccd.bm.lib.Requestor", b =>
            {
                b.HasOne("ccd.bm.lib.Bid", "Bid")
                    .WithMany("Requestors")
                    .HasForeignKey("BidId");
            });

        modelBuilder.Entity("ccd.bm.lib.ResponseItem", b =>
            {
                b.HasOne("ccd.bm.lib.Item", "Item")
                    .WithMany()
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ccd.bm.lib.VendorResponse", "VendorResponse")
                    .WithMany("ResponseItems")
                    .HasForeignKey("VendorResponseId");
            });

        modelBuilder.Entity("ccd.bm.lib.VendorResponse", b =>
            {
                b.HasOne("ccd.bm.lib.Bid", "Bid")
                    .WithMany("VendorResponses")
                    .HasForeignKey("BidId");
            });
#pragma warning restore 612, 618
    }
}
