// <auto-generated />
using System;
using Obiddable.Library.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Obiddable.Library.EF.Migrations
{
    [DbContext(typeof(Dbc))]
    partial class DbcModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Obiddable.Library.Bidding.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Cataloging.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Last_Order_Price")
                        .HasColumnType("decimal(18,5)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,5)");

                    b.Property<bool>("Substitutable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Purchasing.LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account_Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RequestorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestorId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.RequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OverridePrice")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestItems");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Requestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AmountBudgeted")
                        .HasColumnType("TEXT");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Code")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.ToTable("Requestors");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Responding.ResponseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateDescription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AlternateQuantity")
                        .HasColumnType("decimal(18,5)");

                    b.Property<string>("AlternateUnit")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Elected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ElectionReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAlternate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,5)");

                    b.Property<int>("VendorResponseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("VendorResponseId");

                    b.ToTable("ResponseItems");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Responding.VendorResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BidId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BidId");

                    b.ToTable("VendorResponses");
                });

            modelBuilder.Entity("Obiddable.Library.EF.Bidding.Electing.DbcMarkedElection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ElectedResponseItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ElectedResponseItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("MarkedElections");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Cataloging.Item", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Bid", "Bid")
                        .WithMany("Items")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Purchasing.LineItem", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Purchasing.PurchaseOrder", null)
                        .WithMany("LineItems")
                        .HasForeignKey("PurchaseOrderId");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Purchasing.PurchaseOrder", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Bid", "Bid")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Request", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Requesting.Requestor", "Requestor")
                        .WithMany("Requests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requestor");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.RequestItem", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Cataloging.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obiddable.Library.Bidding.Requesting.Request", "Request")
                        .WithMany("RequestItems")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Requestor", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Bid", "Bid")
                        .WithMany("Requestors")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Responding.ResponseItem", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Cataloging.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obiddable.Library.Bidding.Responding.VendorResponse", "VendorResponse")
                        .WithMany("ResponseItems")
                        .HasForeignKey("VendorResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("VendorResponse");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Responding.VendorResponse", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Bid", "Bid")
                        .WithMany("VendorResponses")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bid");
                });

            modelBuilder.Entity("Obiddable.Library.EF.Bidding.Electing.DbcMarkedElection", b =>
                {
                    b.HasOne("Obiddable.Library.Bidding.Responding.ResponseItem", "ElectedResponseItem")
                        .WithMany()
                        .HasForeignKey("ElectedResponseItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Obiddable.Library.Bidding.Cataloging.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectedResponseItem");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Bid", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("Requestors");

                    b.Navigation("VendorResponses");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Purchasing.PurchaseOrder", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Request", b =>
                {
                    b.Navigation("RequestItems");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Requesting.Requestor", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Obiddable.Library.Bidding.Responding.VendorResponse", b =>
                {
                    b.Navigation("ResponseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
